### ISSUE TITLE
Capturing how many times a method has been invoked

### ISSUE THREAD

**Issue by TusharGarg** [seanhenry/MockGenerator#1]
Hi Sean, 

This plugin is quite cool. 
Given the absence of mocking frameworks for Swift, I have been generating mocks by my own. So, this plugin can come handy. 

_One possible enhancement:_
In my assertions, I usually assert that a particular method (`fooBar`) has been called a particular number of times.

- It just makes the test more robust specially for those methods calls which are not idempotent and result in side-effects. 
- Also, at certain times, in case of continuous network calls, one may want to assert that the call was tried atleast *n number of* times. 

Having used Mockito for Java, I quite like these sort of assertions.
   
What do you think about having a field like `numberOfTimesFooBarInvoked: Int` alongside `invokedFooBar: Bool`?

**Comment by seanhenry** [comment]
Hi Tushar,

Thanks for the feedback. 

I think storing the number of times a method is invoked is a good idea. It's something I use from time to time too. Being able to test the parameters that were invoked each time is also useful.

Something like this will work nicely I think:
```
var invokedMethod = false
var invokedMethodCount = 0
var invokedMethodParametersList = [...]()
func method(...) {
  ...
}
```
I'll get to work on this soon. Stay tuned!

**Comment by seanhenry** [comment]
This feature has now been implemented in v2. It will appear in the plugin repository soon or see the releases page for a JAR.
