### ISSUE TITLE
Does not seem to work on AppCode 2017.3, build OC-173.3727.136

### ISSUE THREAD

**Issue by gistya** [seanhenry/MockGenerator#15]
I have not been able to get your plugin to work on this version. I pressed the hotkey but nothing happens. Any thoughts?

**Comment by seanhenry** [comment]
Hi @gistya 

Can you check a few things?

1. You can only generate a mock when the cursor is inside a class. For example if you want to mock a class called `MyClass` you can generate the mock from the following code:

```
class MockMyClass: MyClass {
<place the cursor somewhere in the class and press alt+enter>
}
```
2. A mock can only be generated from a file in a test target. Check that the file you are using is in a test target.

Does either of these solutions fix the problem?

**Comment by seanhenry** [comment]
Another thing to check is that the intention is enabled. Go to `Preferences -> Editor -> Intentions` and find `Generate Mock` in the `Swift group`. Make sure the checkbox next to the intention is switched on.

**Comment by seanhenry** [comment]
I'll close this since there's no reply. Feel free to reopen if there is still a problem.
