### ISSUE TITLE
Feature: add stubbed error for method with throws

### ISSUE THREAD

**Issue by xhonzyn** [seanhenry/MockGenerator#16]
It would be really nice to have an ability to stub error for methods which are declared with throws.

Protocol:
```swift
func load() throws {}
```
Mock:
```swift
var stubbedLoadError: Error?

func load() throws {
  if let error = stubbedLoadError {
    throw error
  }
}
```

**Comment by seanhenry** [comment]
Thanks for the feature request. I will look into this as soon as possible.

**Comment by seanhenry** [comment]
I've added an update to support throwing methods, initialisers and closures. JetBrains will take about a day to process it or you can download it [here](https://github.com/seanhenry/MockGenerator/releases/tag/v9) in the meantime.

**Comment by seanhenry** [comment]
The plugin has been approved and should be ready to update in AppCode now 🎉
