### ISSUE TITLE
Feature: Support optional defaults in return types 

### ISSUE THREAD

**Issue by merlin910** [seanhenry/MockGenerator#17]
With a function signature as follows, I would expect the var `stubbedGetImageInDiskCacheForKeyResult` to be of type `UIImage?` and be equal to `nil` by default. Currently it is typed to a `UIImage!`.
```func getImageInDiskCacheForKey(_ key: String, scale: CGFloat) -> UIImage?```
Thoughts?

**Comment by seanhenry** [comment]
Hi. Thanks for raising this issue. My thinking around this is that `UIImage!` is also optional and should return `nil` by default just like if it were `UIImage?`. Can you elaborate on why `UIImage?` would make a difference?

**Comment by merlin910** [comment]
👍
